modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="yande"
version="1.11"
displayName="yande"
displayURL="https://modrinth.com/mod/yande-mod"
logoFile="logo.png"
credits="candy_kite"
authors="Candy_kite"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.yande]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.yande]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration